import "./globals.css";
import AuthForms from "@/components/AuthForms";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1>Dungeons and Dragons Character Sheet</h1>
        <AuthForms />
      </body>
    </html>
  );
}
