CREATE DATABASE 'dnd-character-sheet';

USE 'dnd-character-sheet';

-- TODO: The Schema below here was generated by AI. We gotta fix some of these. -- 
-- TODO: Turn this schema into code for js --

CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_login TIMESTAMP NULL,
    is_active BOOLEAN DEFAULT TRUE,
    role ENUM('player','dm','admin') DEFAULT 'player',
    profile_picture_url VARCHAR(255) NULL
);

CREATE TABLE Characters (
    CharacterID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    CharacterName VARCHAR(100) NOT NULL,
    ClassLevel VARCHAR(50),
    Race VARCHAR(50),
    Background VARCHAR(50),
    Alignment VARCHAR(50),
    XP INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(id)
);


CREATE TABLE SavingThrows (
    CharacterID INTEGER,
    Strength INTEGER,
    Dexterity INTEGER,
    Constitution INTEGER,
    Intelligence INTEGER,
    Wisdom INTEGER,
    Charisma INTEGER,
    FOREIGN KEY (CharacterID) REFERENCES Characters(CharacterID)
);


CREATE TABLE Skills (
    CharacterID INTEGER,
    Acrobatics INTEGER,
    AnimalHandling INTEGER,
    Arcana INTEGER,
    Athletics INTEGER,
    Deception INTEGER,
    History INTEGER,
    Insight INTEGER,
    Intimidation INTEGER,
    Investigation INTEGER,
    Medicine INTEGER,
    Nature INTEGER,
    Perception INTEGER,
    Performance INTEGER,
    Persuasion INTEGER,
    Religion INTEGER,
    SleightOfHand INTEGER,
    Stealth INTEGER,
    Survival INTEGER,
    PassivePerception INTEGER,
    FOREIGN KEY (CharacterID) REFERENCES Characters(CharacterID)
);


CREATE TABLE Currency (
    CharacterID INTEGER,
    CP INTEGER,
    SP INTEGER,
    EP INTEGER,
    GP INTEGER,
    PP INTEGER,
    FOREIGN KEY (CharacterID) REFERENCES Characters(CharacterID)
);


CREATE TABLE Weapons (
    WeaponID INTEGER PRIMARY KEY AUTOINCREMENT,
    CharacterID INTEGER,
    Name TEXT,
    AtkBonus INTEGER,
    Damage TEXT,
    FOREIGN KEY (CharacterID) REFERENCES Characters(CharacterID)
);


CREATE TABLE Spells (
    SpellID INTEGER PRIMARY KEY AUTOINCREMENT,
    CharacterID INTEGER,
    Name TEXT,
    Level INTEGER,
    SlotsTotal INTEGER,
    SlotsRemaining INTEGER,
    SpellcastingClass TEXT,
    SpellcastingAbility TEXT,
    SpellSaveDC INTEGER,
    SpellAtkBonus INTEGER,
    FOREIGN KEY (CharacterID) REFERENCES Characters(CharacterID)
);


CREATE TABLE CheckBoxes (
    CheckID INTEGER PRIMARY KEY AUTOINCREMENT,
    CharacterID INTEGER,
    Label TEXT,
    Value BOOLEAN,
    FOREIGN KEY (CharacterID) REFERENCES Characters(CharacterID)
);